//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// Исходное имя файла:
// Дата создания: 28.09.2018 14:08:02
namespace InfBaseModelClient
{
    using ClientEntities;
    public partial class InfBaseModel : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Инициализируйте новый объект InfBaseModel.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public InfBaseModel(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "DataLayerWcfApp.DataModel", "Logic.InfBaseModelClient");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Logic.InfBaseModelClient", global::System.StringComparison.Ordinal))
            {
                return string.Concat("DataLayerWcfApp.DataModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для Employees.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Employee> Employees
        {
            get
            {
                if ((this._Employees == null))
                {
                    this._Employees = base.CreateQuery<Employee>("Employees");
                }
                return this._Employees;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Employee> _Employees;
        /// <summary>
        /// В схеме отсутствуют комментарии для Projects.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Project> Projects
        {
            get
            {
                if ((this._Projects == null))
                {
                    this._Projects = base.CreateQuery<Project>("Projects");
                }
                return this._Projects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Project> _Projects;
        /// <summary>
        /// В схеме отсутствуют комментарии для Roles.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<IdentityRole> Roles
        {
            get
            {
                if ((this._Roles == null))
                {
                    this._Roles = base.CreateQuery<IdentityRole>("Roles");
                }
                return this._Roles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<IdentityRole> _Roles;
        /// <summary>
        /// В схеме отсутствуют комментарии для Users.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<IdentityUser> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<IdentityUser>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<IdentityUser> _Users;
        /// <summary>
        /// В схеме отсутствуют комментарии для Employees.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для Projects.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для Roles.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRoles(IdentityRole identityRole)
        {
            base.AddObject("Roles", identityRole);
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для Users.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(IdentityUser identityUser)
        {
            base.AddObject("Users", identityUser);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"DataLayerWcfApp.DataModel\" xmlns=\"http://schemas.microsoft.com/ado/20" +
                "09/11/edm\"><EntityType Name=\"Employee\"><Key><PropertyRef Name=\"Id\" /></Key><Prop" +
                "erty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Ident" +
                "ity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Prope" +
                "rty Name=\"Name\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"tr" +
                "ue\" /><Property Name=\"Surname\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"fal" +
                "se\" Unicode=\"true\" /><Property Name=\"MiddleName\" Type=\"Edm.String\" MaxLength=\"50" +
                "\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"EMail\" Type=\"Edm.String\" " +
                "MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"Le" +
                "adProjects\" Relationship=\"DataLayerWcfApp.DataModel.Project_Leader\" ToRole=\"Proj" +
                "ect_Leader_Source\" FromRole=\"Project_Leader_Target\" /><NavigationProperty Name=\"" +
                "Projects\" Relationship=\"DataLayerWcfApp.DataModel.Project_Employees\" ToRole=\"Pro" +
                "ject_Employees_Source\" FromRole=\"Project_Employees_Target\" /></EntityType><Entit" +
                "yType Name=\"Project\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Typ" +
                "e=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"htt" +
                "p://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"ProjName" +
                "\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Propert" +
                "y Name=\"OrgOrderName\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unico" +
                "de=\"true\" /><Property Name=\"OrgExecuteName\" Type=\"Edm.String\" MaxLength=\"50\" Fix" +
                "edLength=\"false\" Unicode=\"true\" /><Property Name=\"DateProjExecuteBegin\" Type=\"Ed" +
                "m.DateTime\" /><Property Name=\"DateProjExecuteEnd\" Type=\"Edm.DateTime\" /><Propert" +
                "y Name=\"Priority\" Type=\"Edm.Int32\" /><Property Name=\"Comment\" Type=\"Edm.String\" " +
                "MaxLength=\"100\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"LeaderId\" T" +
                "ype=\"Edm.Int32\" /><NavigationProperty Name=\"Employees\" Relationship=\"DataLayerWc" +
                "fApp.DataModel.Project_Employees\" ToRole=\"Project_Employees_Target\" FromRole=\"Pr" +
                "oject_Employees_Source\" /><NavigationProperty Name=\"Leader\" Relationship=\"DataLa" +
                "yerWcfApp.DataModel.Project_Leader\" ToRole=\"Project_Leader_Target\" FromRole=\"Pro" +
                "ject_Leader_Source\" /></EntityType><EntityType Name=\"IdentityRole\"><Key><Propert" +
                "yRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.String\" Nullable=\"false\" Ma" +
                "xLength=\"128\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Name\" Type=\"E" +
                "dm.String\" Nullable=\"false\" MaxLength=\"256\" FixedLength=\"false\" Unicode=\"true\" /" +
                "></EntityType><EntityType Name=\"IdentityUser\"><Key><PropertyRef Name=\"Id\" /></Ke" +
                "y><Property Name=\"Id\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"128\" FixedLe" +
                "ngth=\"false\" Unicode=\"true\" /><Property Name=\"Email\" Type=\"Edm.String\" MaxLength" +
                "=\"256\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"EmailConfirmed\" Type" +
                "=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"PasswordHash\" Type=\"Edm.String" +
                "\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"SecurityS" +
                "tamp\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Pr" +
                "operty Name=\"PhoneNumber\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" " +
                "Unicode=\"true\" /><Property Name=\"PhoneNumberConfirmed\" Type=\"Edm.Boolean\" Nullab" +
                "le=\"false\" /><Property Name=\"TwoFactorEnabled\" Type=\"Edm.Boolean\" Nullable=\"fals" +
                "e\" /><Property Name=\"LockoutEndDateUtc\" Type=\"Edm.DateTime\" /><Property Name=\"Lo" +
                "ckoutEnabled\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"AccessFailed" +
                "Count\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"UserName\" Type=\"Edm.S" +
                "tring\" Nullable=\"false\" MaxLength=\"256\" FixedLength=\"false\" Unicode=\"true\" /></E" +
                "ntityType><Association Name=\"Project_Leader\"><End Type=\"DataLayerWcfApp.DataMode" +
                "l.Employee\" Role=\"Project_Leader_Target\" Multiplicity=\"0..1\" /><End Type=\"DataLa" +
                "yerWcfApp.DataModel.Project\" Role=\"Project_Leader_Source\" Multiplicity=\"*\" /><Re" +
                "ferentialConstraint><Principal Role=\"Project_Leader_Target\"><PropertyRef Name=\"I" +
                "d\" /></Principal><Dependent Role=\"Project_Leader_Source\"><PropertyRef Name=\"Lead" +
                "erId\" /></Dependent></ReferentialConstraint></Association><Association Name=\"Pro" +
                "ject_Employees\"><End Type=\"DataLayerWcfApp.DataModel.Project\" Role=\"Project_Empl" +
                "oyees_Source\" Multiplicity=\"*\" /><End Type=\"DataLayerWcfApp.DataModel.Employee\" " +
                "Role=\"Project_Employees_Target\" Multiplicity=\"*\" /></Association><EntityContaine" +
                "r Name=\"InfBaseModel\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Employe" +
                "es\" EntityType=\"DataLayerWcfApp.DataModel.Employee\" /><EntitySet Name=\"Projects\"" +
                " EntityType=\"DataLayerWcfApp.DataModel.Project\" /><EntitySet Name=\"Roles\" Entity" +
                "Type=\"DataLayerWcfApp.DataModel.IdentityRole\" /><EntitySet Name=\"Users\" EntityTy" +
                "pe=\"DataLayerWcfApp.DataModel.IdentityUser\" /><AssociationSet Name=\"Project_Lead" +
                "er\" Association=\"DataLayerWcfApp.DataModel.Project_Leader\"><End Role=\"Project_Le" +
                "ader_Target\" EntitySet=\"Employees\" /><End Role=\"Project_Leader_Source\" EntitySet" +
                "=\"Projects\" /></AssociationSet><AssociationSet Name=\"Project_Employees\" Associat" +
                "ion=\"DataLayerWcfApp.DataModel.Project_Employees\"><End Role=\"Project_Employees_T" +
                "arget\" EntitySet=\"Employees\" /><End Role=\"Project_Employees_Source\" EntitySet=\"P" +
                "rojects\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edm" +
                "x:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
